### ISSUE TITLE
ENH: Implement a Quadratic Assignment Problem Solver

### ISSUE THREAD

**Issue by asaadeldin11** [NeuroDataDesign/scipy#1]
**Is your feature request related to a problem? Please describe.**
I would like to add a [Quadratic Approximation Problem (QAP)](https://en.wikipedia.org/wiki/Quadratic_assignment_problem) solver function, by implementing the [Fast Approximate QAP (FAQ) algorithm](https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0121002&type=printable) (Vogelstein, 2015). QAP is a combinatorial optimization problem, and the FAQ algorithm can be applied to solve special cases of QAP, including the Graph Matching Problem (GMP) and the Traveling Salesman Problem (TSP).

**Describe the solution you'd like**
Since the QAP is a combinatorial optimization problem, I'd like to have the FAQ implementation exposed through scipy.optimize. The module would accept parameters such as permutation initialization type (single barycenter initialization, or several initializations "close" to the barycenter), maximum Frank-Wolfe iterations, and whether you would like to solve a special case of the QAP (such as GMP). The module would fit with the two cost matrices in the objective function, returning the score (minimized objection function value) and indices of the optimal permutation matrix from the objective function. The implementation will also give the option to include seeds

**Describe alternatives you've considered**

**Additional context (e.g. screenshots)**
I have already implemented FAQ in [Graspy](https://github.com/neurodata/graspy/blob/master/graspy/match/gmp.py), and proof of effectiveness can be found here [here](https://graspy.neurodata.io/tutorials/matching/faq.html)

**Comment by bdpedigo** [comment]
@asaadeldin11 made minor changes. Make the issue in scipy/do whatever thingy sambit was saying, if necessary?
